export const categorieen = [
	"Verse vis",
	"Verse filet",
	"Maaltijden",
	"Kant en klaar",
	"Schotels",
	"Schaal- en schelpdieren",
	"Oesters",
	"Gerookte vis",
	"Salades",
	"Broodjes",
	"Gebakken vis",
	"Sauzen",
	"Zeewierproducten",
	"Soepen",
	"Diepvries",
	"Conserven",
	"Wijnen",
	"Overig",
];
